name: Compilar & Publicar ğŸ‰

on:
  push:
    tags:
      - "v*"

jobs:
  compilar-linux-windows:
    name: Compilar Linux e Windows ğŸ§ğŸªŸ
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositÃ³rio ğŸ“¦
        uses: actions/checkout@v4

      - name: Configurar Go ğŸ¹
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Criar pasta de saÃ­da ğŸ“
        run: mkdir -p dist

      - name: Executar script de build ğŸ”§
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Enviar binÃ¡rios como artefato â¬†ï¸
        uses: actions/upload-artifact@v4
        with:
          name: binarios-linux-windows
          path: dist/*
  compilar-macos:
    name: Compilar macOS ğŸ
    runs-on: macos-latest

    steps:
      - name: Clonar repositÃ³rio ğŸ“¦
        uses: actions/checkout@v4

      - name: Instalar dependÃªncias ğŸ§°
        run: |
          brew install create-dmg

      - name: Configurar Go ğŸ¹
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Criar pasta de saÃ­da ğŸ“
        run: mkdir -p dist

      - name: Executar build para macOS ğŸ”§
        run: |
          chmod +x ./build.sh
          ./build.sh maconly

      - name: Criar arquivo .dmg ğŸ“€
        run: |
          create-dmg "dist/Genius-Play-macOS-amd64.app" "dist" --dmg-title "Genius Play" --volname "Genius Play"

      - name: Enviar binÃ¡rios do macOS como artefato â¬†ï¸
        uses: actions/upload-artifact@v4
        with:
          name: binarios-macos
          path: dist/*macOS*

      - name: Enviar .dmg como artefato â¬†ï¸
        uses: actions/upload-artifact@v4
        with:
          name: Genius-Play-macOS.dmg
          path: dist/Genius-Play-macOS-amd64.dmg

      - name: Publicar no GitHub Releases ğŸš€
        uses: softprops/action-gh-release@v1
        with:
          files: dist/Genius-Play-macOS-amd64.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publicar:
    name: Publicar Release ğŸš€
    needs: [compilar-linux-windows, compilar-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Baixar todos os artefatos ğŸ“¥
        uses: actions/download-artifact@v4
        with:
          path: artefatos

      - name: Criar Release no GitHub ğŸŒŸ
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artefatos/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
