name: Compilar & Publicar ğŸ‰

on:
  push:
    tags:
      - "v*"

jobs:
  compilar-linux-windows:
    name: Compilar Linux e Windows ğŸ§ğŸªŸ
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositÃ³rio ğŸ“¦
        uses: actions/checkout@v4

      - name: Configurar Go ğŸ¹
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Criar pasta de saÃ­da ğŸ“
        run: mkdir -p dist

      - name: Executar script de build ğŸ”§
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Enviar binÃ¡rios como artefato â¬†ï¸
        uses: actions/upload-artifact@v4
        with:
          name: binarios-linux-windows
          path: dist/*
  compilar-macos:
    name: Compilar macOS ğŸ
    runs-on: macos-latest

    steps:
      - name: Clonar repositÃ³rio ğŸ“¦
        uses: actions/checkout@v4

      - name: Instalar dependÃªncias ğŸ§°
        run: |
          brew install create-dmg

      - name: Configurar Go ğŸ¹
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Criar pasta de saÃ­da ğŸ“
        run: mkdir -p dist

      - name: Executar build para macOS ğŸ”§
        run: |
          chmod +x ./build.sh
          ./build.sh maconly
      - name: Enviar .dmg como artefato â¬†ï¸
        uses: actions/upload-artifact@v4
        with:
          name: Genius-Play-macOS.dmg
          path: dist/*

  publicar:
    name: Publicar Release ğŸš€
    needs: [compilar-linux-windows, compilar-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Baixar todos os artefatos ğŸ“¥
        uses: actions/download-artifact@v4
        with:
          path: artefatos

      - name: Criar Release no GitHub ğŸŒŸ
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artefatos/*.exe
            artefatos/*.dmg
            artefatos/*Linux*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
